from __future__ import annotations


STANDARD_WINDOWS: tuple[tuple[int, str], ...] = (
    (5, "week"),
    (22, "month"),
    (66, "quarter"),
    (120, "half_year"),
    (250, "year"),
)

OPERATOR_ROLES: tuple[tuple[str, str], ...] = (
    ("group_backfill", "missing_value_repair"),
    ("kth_element", "time_series_value_lookup"),
    ("last_diff_value", "time_series_value_lookup"),
    ("normalize", "cross_sectional_normalization"),
    ("quantile", "cross_sectional_normalization"),
    ("rank", "cross_sectional_normalization"),
    ("scale", "cross_sectional_scaling"),
    ("ts_arg_max", "time_series_event_age"),
    ("ts_arg_min", "time_series_event_age"),
    ("ts_av_diff", "time_series_change"),
    ("ts_backfill", "missing_value_repair"),
    ("ts_corr", "time_series_pairwise"),
    ("ts_count_nans", "missing_value_count"),
    ("ts_covariance", "time_series_pairwise"),
    ("ts_decay_linear", "time_series_smoothing"),
    ("ts_delay", "time_series_lag"),
    ("ts_delta", "time_series_change"),
    ("ts_mean", "time_series_smoothing"),
    ("ts_product", "time_series_product"),
    ("ts_quantile", "time_series_normalization"),
    ("ts_rank", "time_series_normalization"),
    ("ts_regression", "time_series_pairwise"),
    ("ts_scale", "time_series_normalization"),
    ("ts_std_dev", "time_series_dispersion"),
    ("ts_sum", "time_series_aggregation"),
    ("ts_zscore", "time_series_normalization"),
    ("winsorize", "cross_sectional_outlier_control"),
    ("zscore", "cross_sectional_normalization"),
)

OPERATOR_OUTPUTS: tuple[tuple[str, str], ...] = (
    ("abs", "signal"),
    ("add", "signal"),
    ("and", "condition"),
    ("bucket", "group"),
    ("days_from_last_change", "signal"),
    ("densify", "group"),
    ("divide", "signal"),
    ("equal", "condition"),
    ("greater", "condition"),
    ("greater_equal", "condition"),
    ("group_backfill", "signal"),
    ("group_mean", "signal"),
    ("group_neutralize", "signal"),
    ("group_rank", "signal"),
    ("group_scale", "signal"),
    ("group_zscore", "signal"),
    ("hump", "signal"),
    ("if_else", "signal"),
    ("inverse", "signal"),
    ("is_nan", "condition"),
    ("kth_element", "signal"),
    ("last_diff_value", "signal"),
    ("less", "condition"),
    ("less_equal", "condition"),
    ("log", "signal"),
    ("max", "signal"),
    ("min", "signal"),
    ("multiply", "signal"),
    ("normalize", "signal"),
    ("not", "condition"),
    ("not_equal", "condition"),
    ("or", "condition"),
    ("power", "signal"),
    ("quantile", "signal"),
    ("rank", "signal"),
    ("reverse", "signal"),
    ("scale", "signal"),
    ("sign", "signal"),
    ("signed_power", "signal"),
    ("sqrt", "signal"),
    ("subtract", "signal"),
    ("trade_when", "signal"),
    ("ts_arg_max", "signal"),
    ("ts_arg_min", "signal"),
    ("ts_av_diff", "signal"),
    ("ts_backfill", "signal"),
    ("ts_corr", "signal"),
    ("ts_count_nans", "signal"),
    ("ts_covariance", "signal"),
    ("ts_decay_linear", "signal"),
    ("ts_delay", "signal"),
    ("ts_delta", "signal"),
    ("ts_mean", "signal"),
    ("ts_product", "signal"),
    ("ts_quantile", "signal"),
    ("ts_rank", "signal"),
    ("ts_regression", "signal"),
    ("ts_scale", "signal"),
    ("ts_std_dev", "signal"),
    ("ts_step", "signal"),
    ("ts_sum", "signal"),
    ("ts_zscore", "signal"),
    ("vec_avg", "signal"),
    ("vec_sum", "signal"),
    ("vector_neut", "signal"),
    ("winsorize", "signal"),
    ("zscore", "signal"),
)
